export enum UserRoles {
  GIGA_ADMIN = 'GIGA.SUPER.ADMIN',
  GIGA_VIEW_ONLY = 'GIGA.VIEW.ONLY',
  ISP_CONTRACT_MANAGER = 'ISP.CONTRACT.MANAGER',
  ISP_CUSTOMER_SERVICE = 'ISP.CUSTOMER.SERVICE',
  COUNTRY_CONTRACT_CREATOR = 'COUNTRY.CONTRACT.CREATOR',
  COUNTRY_ACCOUNTANT = 'COUNTRY.ACCOUNTANT',
  COUNTRY_SUPER_ADMIN = 'COUNTRY.SUPER.ADMIN',
  COUNTRY_MONITOR = 'COUNTRY.MONITOR',
  SCHOOL_CONNECTIVITY_MANAGER = 'SCHOOL.CONNECTIVITY.MANAGER'
}

export enum Views {
  contract = 'contract',
  payment = 'payment',
  wallet = 'wallet'
}
