import {
  Add,
  AddAlt,
  ArrowRight,
  Automatic,
  CaretDown,
  Checkmark,
  CheckmarkFilled,
  CheckmarkOutline,
  ChevronDown,
  ChevronUp,
  Clean,
  Close,
  ConnectionSignal,
  Copy,
  Document,
  Download,
  Edit,
  Education,
  ErrorFilled,
  FaceActivated,
  FaceCool,
  FaceDissatisfied,
  FaceNeutral,
  FaceSatisfied,
  Filter,
  Help,
  Home,
  Information,
  InformationFilled,
  Logout,
  MailAll,
  Money,
  Notification,
  NotificationNew,
  OverflowMenuVertical,
  PreviousOutline,
  Receipt,
  Replicate,
  Reset,
  Save,
  Search,
  SendAlt,
  Settings,
  Share,
  ShareKnowledge,
  Subtract,
  TrashCan,
  UserAdmin,
  UserMultiple,
  View,
  Wallet,
  WarningFilled
} from '@carbon/icons-react'
import {
  Assets,
  DesignResearch,
  Invoice,
  Renew,
  Time,
  TransactionalTrust
} from '@carbon/pictograms-react'
import { NoInfo } from 'src/icons'

export const ICONS = {
  Add,
  AddCircular: AddAlt,
  Automatic,
  Back: PreviousOutline,
  CaretDown,
  ChevronDown,
  ChevronUp,
  Clean,
  Close,
  Connection: ConnectionSignal,
  Continue: ArrowRight,
  Contract: Document,
  Copy,
  Delete: TrashCan,
  Download,
  Duplicate: Replicate,
  Edit,
  Education,
  ErrorFilled,
  FeedbackHighRating: FaceActivated,
  FeedbackLowRating: FaceNeutral,
  FeedbackNeutralRating: FaceSatisfied,
  FeedbackVeryHighRating: FaceCool,
  FeedbackVeryLowRating: FaceDissatisfied,
  Filter,
  Fund: Money,
  Help,
  Home,
  Information,
  InformationFilled,
  KnowledgeBase: ShareKnowledge,
  Logout,
  Mail: MailAll,
  Notification,
  NotificationNew,
  OverflowMenuVertical,
  Payment: Receipt,
  Reset,
  Save,
  Search,
  Send: SendAlt,
  Settings,
  Share,
  Subtract,
  Success: Checkmark,
  SuccessFilled: CheckmarkFilled,
  SuccessOutline: CheckmarkOutline,
  UserApproval: UserAdmin,
  Users: UserMultiple,
  View,
  Wallet,
  WarningFilled
} as const

export const PICTOGRAMS = {
  Renew,
  Time,
  TransactionalTrust,
  Invoice,
  Assets,
  DesignResearch,
  NoInfo
} as const
