export { default as Footer } from './Footer'
export { default as PopoverTitle } from './PopoverTitle'
export { default as SectionHeading } from './SectionHeading'
export { default as SectionSubtitle } from './SectionSubtitle'
export { default as SectionTitle } from './SectionTitle'
export { default as Typography } from './Typography'
