name: Linting on PR

on:
  pull_request:
    branches:
      - dev

jobs:
  linting:
    runs-on: 'ubuntu-latest'
    name: Linting
    steps:
      - uses: actions/checkout@v2

      - name: Install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: yarn install
        run: yarn install

      - name: Run ESLint
        run: yarn run lint

      - name: Comment PR - Failure
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            :x: The PR didn't pass linting, please review and update :exclamation:

      - name: Comment PR - Success
        if: ${{ success() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            :white_check_mark: The PR passed linting, good job! :rocket:
